cmake_minimum_required(VERSION 3.13)
project(careershopper_tray_tests LANGUAGES CXX)
find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK REQUIRED IMPORTED_TARGET gtk+-3.0)
pkg_check_modules(APPINDICATOR REQUIRED IMPORTED_TARGET ayatana-appindicator3-0.1)
pkg_check_modules(DBUSMENU REQUIRED IMPORTED_TARGET dbusmenu-gtk3-0.4)
add_executable(desktop_tray_test desktop_tray_test.cc ../../linux/runner/desktop_tray.cc)
target_compile_features(desktop_tray_test PRIVATE cxx_std_14)
target_compile_options(desktop_tray_test PRIVATE -Wall -Werror)
target_link_libraries(desktop_tray_test PRIVATE PkgConfig::GTK PkgConfig::APPINDICATOR PkgConfig::DBUSMENU)
enable_testing()
add_test(NAME desktop_tray COMMAND desktop_tray_test)
